services:
  frontend:
    ports:
      - "4200:80"
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  celery-worker:
    volumes:
      - ./backend:/app
  celery-beat:
    volumes:
      - ./backend:/app
