# Generated by Django 6.0.3 on 2026-03-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_related_object_id'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('mention', 'Mention'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed'), ('deadline_warning', 'Deadline Warning'), ('summary_ready', 'Summary Ready'), ('project_assigned', 'Project Assigned'), ('project_unassigned', 'Project Unassigned'), ('epic_assigned', 'Epic Assigned'), ('epic_unassigned', 'Epic Unassigned')], db_index=True, max_length=30),
        ),
    ]
