# Generated by Django 6.0.3 on 2026-03-15 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tasks', '0003_enforce_organization_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action', 'new_value', 'timestamp'], name='ix_audit_action_val_ts'),
        ),
    ]
