# Generated by Django 6.0.3 on 2026-03-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_action_value_timestamp_index'),
        ('projects', '0001_initial'),
        ('tasks', '0003_enforce_organization_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='tasks.task'),
        ),
    ]
