# Generated by Django 6.0.3 on 2026-03-17 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_enforce_organization_notnull'),
        ('organizations', '0003_alter_organization_verbose_names'),
        ('projects', '0001_initial'),
        ('tags', '0003_enforce_organization_notnull'),
        ('tasks', '0003_enforce_organization_notnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.epic'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'epic'], name='ix_task_org_epic'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'parent_task'], name='ix_task_org_parent'),
        ),
    ]
