# Generated by Django 6.0.3 on 2026-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_summaries', '0003_enforce_organization_notnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsummary',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='sections',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
